### ISSUE TITLE
Allow transfering fees to account instead of burning them

### ISSUE THREAD

**Issue by janhack** [LiskHQ/lips#209]
# Description

Introduce the possibility that in the Fee module, fees are transferred to a specified account instead of burning them. This could be achieved by:

- Adding configurable constant `BURN_FEES` (boolean) and `ADDRESS_FEE_POOL` (20 byte address), the names are up to discussion here.
- In LIP 48 replace 

```python
Token.burn(address, tokenID, amount),
```
by
```python
if BURN_FEES:
    Token.burn(address, tokenID, amount)
else:
    Token.transfer(address, ADDRESS_FEE_POOL, tokenID, amount)
```

# Motivation

For sidechains, it can be beneficial to have the options to collect fees in a pool (in particular, when using `LSK` for fees) and use them to incentivize validators or other protocol participants. 

Note that an issue with the same suggestion was also created in the SDK repository: https://github.com/LiskHQ/lisk-sdk/issues/8028.

**Comment by mjerkov** [comment]
Do these configurable constants have mainchain values (I suppose that `BURN_FEES = false` on mainchain)?
I have no objections on the namings of constants.

**Comment by janhack** [comment]
@shuse2 What would you think is the most elegant approach here for the Lisk mainchain, leave `ADDRESS_FEE_POOL` undefined (not sure if this is possible for configurable constants) or set some default value such as the all zero address?

**Comment by shuse2** [comment]
we can keep it undefined, and implementation wise, we can do like if ADDRESS_FEE_POOL is defined, make transfer otherwise burn

In this way, we don't need the flag

**Comment by mjerkov** [comment]
The option to leave out the `BURN_FEES` flag seems good to me, if @janhack agrees I can open the PR.

**Comment by janhack** [comment]
Sounds good.
