### ISSUE TITLE
Define `Transaction` type in LIP 0041

### ISSUE THREAD

**Issue by mjerkov** [LiskHQ/lips#212]
The type `Transaction` is used in several places, but it is not defined. In particular, it is not clear that for an instance of `Transaction` the `params` property is of type _object_ instead of _bytes_.

The change depends on the conclusions of [Improve LIP template discussion](https://trello.com/c/JPH2zlYC/1478-improve-lip-template).

**Comment by janhack** [comment]
Closed in favor of https://github.com/LiskHQ/lips/issues/226.
