### ISSUE TITLE
Missing initialization of "own chain account" in LIP 0063

### ISSUE THREAD

**Issue by AndreasKendziorra** [LiskHQ/lips#221]
In LIP 0045, it is [specified](https://github.com/LiskHQ/lips/blob/e57af53de675d64c6c3bcc9201058739460c4e4c/proposals/lip-0045.md?plain=1#L567) that "the own chain account is present by default, set to an object with properties: ...". This can, however, not be implemented in the interoperability module in general and can also not be specified in the "Genesis Block Processing" section of LIP 0045 as this a rule specific to the mainchain and does not hold in general.
Therefore, it must be specified in LIP 0063.

**Comment by ricott1** [comment]
Fix typo:

- "Moreover, it defines the migration process from Lisk Core v3 to Lisk Core v4\." --> "Moreover, it defines the migration process from Lisk Core v3 to Lisk Core v4."
