### ISSUE TITLE
LIP 0044 defines unused substore prefix

### ISSUE THREAD

**Issue by sergeyshemyakov** [LiskHQ/lips#241]
In LIP 0044, there is a `SUBSTORE_PREFIX_GENESIS_DATA` substore prefix defined. However it is not used in the LIP. 
I think, this constant should be removed from the LIP.

**Comment by AndreasKendziorra** [comment]
Also, the function [getGeneratorsBetweenTimestamps](https://github.com/LiskHQ/lips/blob/52e3a822a20a7c71d992692e635016719b830ac1/proposals/lip-0044.md?plain=1#L535) still uses the object `generatorList` which was the single entry in the _generator list substore_. This substore was, however, replaced by the _validators params substore_ which contains the `validators` array instead in [this PR](https://github.com/LiskHQ/lips/pull/177).
