### ISSUE TITLE
LIP0045: Rename constants from MIN/MAX_XXX_LENGTH pattern to XXX_MIN/MAX_LENGTH

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lips#323]
<img width="1164" alt="Screenshot 2023-04-15 at 02 55 41 PM" src="https://user-images.githubusercontent.com/1403133/232220580-c652978d-8eff-4b90-b6a0-a7ba29330eda.png">

Since `MIN/MAX` applies to `LENGTH`, I suggest to rename these constants to `XXX_MIN_LENGTH` &  `XXX_MAX_LENGTH` format.

Hence 
`MIN_MODULE_NAME_LENGTH` will change to `MODULE_NAME_MIN_LENGTH`, 
`MAX_MODULE_NAME_LENGTH` to `MODULE_NAME_MAX_LENGTH` 

& same for others.

Also applicable to LIP 65
As a side note, `MAX_LENGTH_AGGREGATION_BITS` (LIP 61) can be changed to `AGGREGATION_BITS_MAX_LENGTH`

**Comment by gkoumout** [comment]
In fact, there are many other places where a similar change should be done and improve consistency for constant names. Therefore, it is best to revisit this topic in a future issue and fix this inconsistency globally throughout all LIPs.
