### ISSUE TITLE
LIP0053: Unused variable [defaultEventsTopic] can be removed or be part of comment

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lips#324]
https://github.com/LiskHQ/lips/blob/main/proposals/lip-0053.md#execution
> Set ccmID (instead of the transaction ID) as default topic of this event.
defaultEventsTopic = ccmID

I see 2 issues here:
- As per comment, "default topic" refers to default topic (of event), while variable (defaultEventsTopic) refers to default event (& not default topic). Hence correct naming is "eventsDefaultTopic".
- There is no further usage of this variable. If we search for "defaultEventsTopic", we only find "defaultEventsTopic = ccmID" (4 times in LIP).

If these variables are declared based on assumption that they will be used at some point (without actually being used in code/lip), then we should mention them only as comment, otherwise, it creates confusion that perhaps some code segment is missing which actually use this variable. Hence I suggest;
- Either remove all 4 assignments of `defaultEventsTopic = ccmID` from page
- Mention them as part of the given comment on same line. In given case, it will look like `Set ccmID (instead of the transaction ID) as default topic of this event, i.e., eventsDefaultTopic = ccmID` (preferable)

Also here - https://github.com/LiskHQ/lips/blob/main/proposals/lip-0054.md#execution-1

**Comment by ricott1** [comment]
The default topic is used in `emitEvent` (in the PR I add a comment explaining this). Also notice that the LIPs present specs in pseudocode format, but it should not be expected that the code is runnable as is.
