### ISSUE TITLE
LIP0045: `initialized` property can be removed from `terminatedStateAccountSchema`

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lips#337]
// https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md#json-schema-5
```
terminatedStateAccountSchema = {
    "type": "object",
    "required": ["stateRoot", "mainchainStateRoot", "initialized"],
    "properties": {
        "stateRoot": {
            "dataType": "bytes",
            "length": HASH_LENGTH,
            "fieldNumber": 1
        },
        "mainchainStateRoot": {
            "dataType": "bytes",
            "length": HASH_LENGTH,
            "fieldNumber": 2
        },
        "initialized": {
            "dataType": "boolean",
            "fieldNumber": 3
        }
    }
}
```
[Properties](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md#properties-5)
`stateRoot`: The state root of the terminated chain. If the terminated state account is initialized, this property is set to either chainAccount(chainID).lastCertificate.stateRoot, where chainID is the chain ID of the terminated chain, or to the state root given in the parameters of the sidechain terminated CCM. If the account is not initialized, it is set to EMPTY_HASH instead.
`mainchainStateRoot`: If the terminated state account is not initialized, this property is set to the last certified state root of the mainchain at the moment in which the chain was terminated, i.e. to chainAccount(getMainchainID()).lastCertificate.stateRoot. If the account is initialized, it is set to EMPTY_HASH instead.
`initialized`: A boolean value, indicating whether the terminated state account has been initialized, i.e. if the stateRoot property has been set.

---

**Problem:**
While looking at these two properties, we can see that both are doing the same thing & `initialized` seems like a wrapper to indicate terminated state. But since we can know the status through `EMPTY_HASH` (_If the account is not initialized, it is set to EMPTY_HASH instead._), I suggest to remove this (additional wrapper) `initialized` from schema.

**Reasons/Motivation**:
- There wouldn't be a need to get/set this extra `initialized` property
- Only `EMPTY_HASH` is enough to know that some account is NOT initialized
- Making decision on two parameters is error prone, it could be the case that in DB `initialized` is set to `true`, while `stateRoot` having `EMPTY_HASH` value, resulting in further (hidden) bugs in source code
- Even if there is `initialized` field in schema, we still have checks like `if (stateRoot.equals(EMPTY_HASH))`  in [code](https://github.com/LiskHQ/lisk-sdk/blob/8bfefc67c0bc713d6e84dc920aeabd6acf0bc87e/framework/src/modules/interoperability/base_interoperability_internal_methods.ts#L206)

**Comment by ricott1** [comment]
We are aware that it could be possible to remove this property, however there could be edge cases where a sidechain gets terminated with the state root still set to empty hash, in which case it is good to explicitly keep the `initialized` boolean flag for simplicity.
