### ISSUE TITLE
Cross-chain transfer of LIP 0051 does not verify if the receiving chain is active

### ISSUE THREAD

**Issue by mjerkov** [LiskHQ/lips#393]
## Motivation
The requirement that the receiving chain is active is a necessary prerequisite for a successful cross-chain transfer.

## Current Specifications
Currently, neither [cross chain transfer command verification](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0051.md#verification-1) and [cross chain transfer method](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0051.md#transfercrosschain-2) of Token module LIP 0051 does not check whether the receiving chain is active, i.e. if it has the status `CHAIN_STATUS_ACTIVE` as defined in LIP 0045.

## Proposed Specifications
1. In [cross chain transfer command verification](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0051.md#verification-1), introduce the following:
```python
if not Interoperability.isChannelActive(receivingChainID):
    raise Exception("Receiving chain is not active.")
```
2. In  [cross chain transfer method](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0051.md#transfercrosschain-2), introduce the following:
```python
if not Interoperability.isChannelActive(receivingChainID):
    emitFailedCrossChainTransferEvent(senderAddress, tokenID, amount, receivingChainID, recipientAddress, RECEIVING_CHAIN_NOT_ACTIVE)
    raise Exception("Receiving chain is not active.")
```
and add `RECEIVING_CHAIN_NOT_ACTIVE` to the [table](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0051.md#event-names-and-results) of event result codes.

## Affected LIPs
LIP 0051

**Comment by janhack** [comment]
We close the issue and do not use the `isChannelActive` method for the following reasons:

- Avoid using more internals of the Interoperability module, in particular, avoid setting a precedent for more complicated interactions between interoperable modules and the Interoperability without that being necessary (it is okay that the send method can fail).
- Keeping transaction verification minimal and not doing stateful checks that can be detected via dry-running.
- Relying on the UI to better address that the receiving chain is active as the UI can check the Lisk Mainchain state, which cannot be checked on-chain for sidechains.
