### ISSUE TITLE
Revert aggregateCommitHeight in genesis block to 0

### ISSUE THREAD

**Issue by gkoumout** [LiskHQ/lips#495]
## Motivation

In a recent issue, we addressed [performance in single commit creation](https://github.com/LiskHQ/lips/issues/491). The goal was to not create single commits for heights smaller than the (re)genesis height. One of the actions taken was to set `b.header.aggregateCommit.height = b.header.height` for the genesis block; the previous value was `b.header.aggregateCommit.height = 0`. 

Since this change was proposed after the testnet migration, this makes the testnet genesis block invalid according to the new protocol.

## Current Specifications

At the time of migration, for the genesis block `b`, `b.header.aggregateCommit.height = 0`. By setting in the specs that `b.header.aggregateCommit.height = b.header.height` for the genesis block, makes the current genesis block invalid. 

## Proposed Specifications

Revert this change and reset `b.header.aggregateCommit.height = 0` for the genesis block `b`. Note that this will not affect the single commit creation, since (after a [subsequent edit](https://github.com/LiskHQ/lips/pull/493)) for any block `b`, single commits are created after `getMaxRemovalHeight() = max(b.header.aggregateCommit.height, MIN_CERTIFICATE_HEIGHT - 1) >= genesisHeight`, since `MIN_CERTIFICATE_HEIGHT >= genesisHeight +1`.   

## Affected LIPs

LIP 0060.

**Comment by janhack** [comment]
As we reset the Testnet and re-create the new genesis block for Testnet due to other reasons, we do not need to revert the change of b.header.aggregateCommit.height. Therefore, the issue is closed.
